# Form implementation generated from reading ui file 'hcmgis_medialaxis_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hcmgis_medialaxis_form(object):
    def setupUi(self, hcmgis_medialaxis_form):
        hcmgis_medialaxis_form.setObjectName("hcmgis_medialaxis_form")
        hcmgis_medialaxis_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        hcmgis_medialaxis_form.setEnabled(True)
        hcmgis_medialaxis_form.resize(479, 343)
        hcmgis_medialaxis_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_medialaxis_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LblStatus = QtWidgets.QLabel(parent=hcmgis_medialaxis_form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 10, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=hcmgis_medialaxis_form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 2)
        self.LblInput = QtWidgets.QLabel(parent=hcmgis_medialaxis_form)
        self.LblInput.setObjectName("LblInput")
        self.gridLayout.addWidget(self.LblInput, 0, 0, 1, 2)
        self.LblInput_2 = QtWidgets.QLabel(parent=hcmgis_medialaxis_form)
        self.LblInput_2.setObjectName("LblInput_2")
        self.gridLayout.addWidget(self.LblInput_2, 4, 0, 1, 2)
        self.LblInput_3 = QtWidgets.QLabel(parent=hcmgis_medialaxis_form)
        self.LblInput_3.setObjectName("LblInput_3")
        self.gridLayout.addWidget(self.LblInput_3, 2, 0, 1, 2)
        self.LblOutput = QtWidgets.QLabel(parent=hcmgis_medialaxis_form)
        self.LblOutput.setObjectName("LblOutput")
        self.gridLayout.addWidget(self.LblOutput, 7, 0, 1, 2)
        self.status = QtWidgets.QProgressBar(parent=hcmgis_medialaxis_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 11, 0, 1, 2)
        self.CboField = QgsFieldComboBox(parent=hcmgis_medialaxis_form)
        self.CboField.setObjectName("CboField")
        self.gridLayout.addWidget(self.CboField, 3, 0, 1, 2)
        self.CboInput = QgsMapLayerComboBox(parent=hcmgis_medialaxis_form)
        self.CboInput.setShowCrs(True)
        self.CboInput.setObjectName("CboInput")
        self.gridLayout.addWidget(self.CboInput, 1, 0, 1, 2)
        self.output_file_name = QgsFileWidget(parent=hcmgis_medialaxis_form)
        self.output_file_name.setObjectName("output_file_name")
        self.gridLayout.addWidget(self.output_file_name, 8, 0, 1, 1)
        self.spinBox = QgsDoubleSpinBox(parent=hcmgis_medialaxis_form)
        self.spinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBox.setDecimals(1)
        self.spinBox.setMinimum(0.1)
        self.spinBox.setMaximum(10.0)
        self.spinBox.setSingleStep(0.1)
        self.spinBox.setProperty("value", 0.5)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(parent=hcmgis_medialaxis_form)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_medialaxis_form)
        self.BtnApplyClose.accepted.connect(hcmgis_medialaxis_form.accept) # type: ignore
        self.BtnApplyClose.rejected.connect(hcmgis_medialaxis_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(hcmgis_medialaxis_form)

    def retranslateUi(self, hcmgis_medialaxis_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_medialaxis_form.setWindowTitle(_translate("hcmgis_medialaxis_form", "Skeleton/Medial Axis"))
        self.label.setText(_translate("hcmgis_medialaxis_form", "(Notice: Output should be refined after running)"))
        self.LblInput.setText(_translate("hcmgis_medialaxis_form", "Input Polygon (1..100 selected features limit!)"))
        self.LblInput_2.setText(_translate("hcmgis_medialaxis_form", "Density (m)"))
        self.LblInput_3.setText(_translate("hcmgis_medialaxis_form", "Unique field"))
        self.LblOutput.setText(_translate("hcmgis_medialaxis_form", "Output"))
from qgsdoublespinbox import QgsDoubleSpinBox
from qgsfieldcombobox import QgsFieldComboBox
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_medialaxis_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_medialaxis_form()
    ui.setupUi(hcmgis_medialaxis_form)
    hcmgis_medialaxis_form.show()
    sys.exit(app.exec())
