# Form implementation generated from reading ui file 'hcmgis_xls2csv_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hcmgis_xls2csv_form(object):
    def setupUi(self, hcmgis_xls2csv_form):
        hcmgis_xls2csv_form.setObjectName("hcmgis_xls2csv_form")
        hcmgis_xls2csv_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        hcmgis_xls2csv_form.setEnabled(True)
        hcmgis_xls2csv_form.resize(513, 465)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        hcmgis_xls2csv_form.setFont(font)
        hcmgis_xls2csv_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_xls2csv_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=hcmgis_xls2csv_form)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BtnInputFolder = QtWidgets.QPushButton(parent=hcmgis_xls2csv_form)
        self.BtnInputFolder.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.BtnInputFolder.setFont(font)
        self.BtnInputFolder.setObjectName("BtnInputFolder")
        self.gridLayout_3.addWidget(self.BtnInputFolder, 0, 1, 1, 1)
        self.LinInputFolder = QtWidgets.QLineEdit(parent=hcmgis_xls2csv_form)
        self.LinInputFolder.setEnabled(True)
        self.LinInputFolder.setMouseTracking(True)
        self.LinInputFolder.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.LinInputFolder.setAcceptDrops(False)
        self.LinInputFolder.setText("")
        self.LinInputFolder.setReadOnly(True)
        self.LinInputFolder.setObjectName("LinInputFolder")
        self.gridLayout_3.addWidget(self.LinInputFolder, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.LblXLS = QtWidgets.QLabel(parent=hcmgis_xls2csv_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblXLS.setFont(font)
        self.LblXLS.setText("")
        self.LblXLS.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.LblXLS.setObjectName("LblXLS")
        self.verticalLayout.addWidget(self.LblXLS)
        self.lsXLS = QtWidgets.QListWidget(parent=hcmgis_xls2csv_form)
        self.lsXLS.setObjectName("lsXLS")
        self.verticalLayout.addWidget(self.lsXLS)
        self.LblStatus = QtWidgets.QLabel(parent=hcmgis_xls2csv_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblStatus.setFont(font)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.verticalLayout.addWidget(self.LblStatus)
        self.status = QtWidgets.QProgressBar(parent=hcmgis_xls2csv_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.label = QtWidgets.QLabel(parent=hcmgis_xls2csv_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtError = QtWidgets.QTextEdit(parent=hcmgis_xls2csv_form)
        self.txtError.setObjectName("txtError")
        self.verticalLayout.addWidget(self.txtError)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(parent=hcmgis_xls2csv_form)
        self.BtnApplyClose.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.BtnApplyClose.setCenterButtons(False)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_xls2csv_form)
        self.BtnApplyClose.accepted.connect(hcmgis_xls2csv_form.accept) # type: ignore
        self.BtnApplyClose.rejected.connect(hcmgis_xls2csv_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(hcmgis_xls2csv_form)

    def retranslateUi(self, hcmgis_xls2csv_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_xls2csv_form.setWindowTitle(_translate("hcmgis_xls2csv_form", "Batch Convert XLSX to CSV"))
        self.label_2.setText(_translate("hcmgis_xls2csv_form", "Input XLSX Folder"))
        self.BtnInputFolder.setText(_translate("hcmgis_xls2csv_form", "Browse..."))
        self.label.setText(_translate("hcmgis_xls2csv_form", "Errors Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_xls2csv_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_xls2csv_form()
    ui.setupUi(hcmgis_xls2csv_form)
    hcmgis_xls2csv_form.show()
    sys.exit(app.exec())
