# Form implementation generated from reading ui file 'hcmgis_merge_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hcmgis_merge_form(object):
    def setupUi(self, hcmgis_merge_form):
        hcmgis_merge_form.setObjectName("hcmgis_merge_form")
        hcmgis_merge_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        hcmgis_merge_form.setEnabled(True)
        hcmgis_merge_form.resize(522, 229)
        hcmgis_merge_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_merge_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=hcmgis_merge_form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.sourcelayers = QtWidgets.QListWidget(parent=hcmgis_merge_form)
        self.sourcelayers.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.sourcelayers.setObjectName("sourcelayers")
        self.verticalLayout.addWidget(self.sourcelayers)
        self.label = QtWidgets.QLabel(parent=hcmgis_merge_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.outfilename = QtWidgets.QLineEdit(parent=hcmgis_merge_form)
        self.outfilename.setText("")
        self.outfilename.setReadOnly(False)
        self.outfilename.setObjectName("outfilename")
        self.gridLayout.addWidget(self.outfilename, 0, 0, 1, 1)
        self.browseoutfile = QtWidgets.QPushButton(parent=hcmgis_merge_form)
        self.browseoutfile.setObjectName("browseoutfile")
        self.gridLayout.addWidget(self.browseoutfile, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(parent=hcmgis_merge_form)
        self.BtnApplyClose.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_merge_form)
        self.BtnApplyClose.accepted.connect(hcmgis_merge_form.accept) # type: ignore
        self.BtnApplyClose.rejected.connect(hcmgis_merge_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(hcmgis_merge_form)
        hcmgis_merge_form.setTabOrder(self.sourcelayers, self.outfilename)
        hcmgis_merge_form.setTabOrder(self.outfilename, self.browseoutfile)
        hcmgis_merge_form.setTabOrder(self.browseoutfile, self.BtnApplyClose)

    def retranslateUi(self, hcmgis_merge_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_merge_form.setWindowTitle(_translate("hcmgis_merge_form", "Merge Layers"))
        self.label_4.setText(_translate("hcmgis_merge_form", "Select Layers to be merged"))
        self.label.setText(_translate("hcmgis_merge_form", "Output Shapefile"))
        self.browseoutfile.setText(_translate("hcmgis_merge_form", "Browse..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_merge_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_merge_form()
    ui.setupUi(hcmgis_merge_form)
    hcmgis_merge_form.show()
    sys.exit(app.exec())
