# Form implementation generated from reading ui file 'hcmgis_split_polygon_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hcmgis_spit_polygon_form(object):
    def setupUi(self, hcmgis_spit_polygon_form):
        hcmgis_spit_polygon_form.setObjectName("hcmgis_spit_polygon_form")
        hcmgis_spit_polygon_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        hcmgis_spit_polygon_form.setEnabled(True)
        hcmgis_spit_polygon_form.resize(529, 318)
        hcmgis_spit_polygon_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_spit_polygon_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LblRandomPoints = QtWidgets.QLabel(parent=hcmgis_spit_polygon_form)
        self.LblRandomPoints.setObjectName("LblRandomPoints")
        self.gridLayout.addWidget(self.LblRandomPoints, 6, 0, 1, 1)
        self.spParts = QgsDoubleSpinBox(parent=hcmgis_spit_polygon_form)
        self.spParts.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spParts.setDecimals(1)
        self.spParts.setMinimum(1.0)
        self.spParts.setMaximum(10000.0)
        self.spParts.setSingleStep(1.0)
        self.spParts.setProperty("value", 5.0)
        self.spParts.setObjectName("spParts")
        self.gridLayout.addWidget(self.spParts, 5, 1, 1, 1)
        self.LblOutput = QtWidgets.QLabel(parent=hcmgis_spit_polygon_form)
        self.LblOutput.setObjectName("LblOutput")
        self.gridLayout.addWidget(self.LblOutput, 9, 0, 1, 2)
        self.spRandomPoints = QgsDoubleSpinBox(parent=hcmgis_spit_polygon_form)
        self.spRandomPoints.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spRandomPoints.setDecimals(0)
        self.spRandomPoints.setMinimum(100.0)
        self.spRandomPoints.setMaximum(100000.0)
        self.spRandomPoints.setSingleStep(10.0)
        self.spRandomPoints.setProperty("value", 1000.0)
        self.spRandomPoints.setObjectName("spRandomPoints")
        self.gridLayout.addWidget(self.spRandomPoints, 6, 1, 1, 1)
        self.CboInput = QgsMapLayerComboBox(parent=hcmgis_spit_polygon_form)
        self.CboInput.setShowCrs(True)
        self.CboInput.setObjectName("CboInput")
        self.gridLayout.addWidget(self.CboInput, 1, 0, 1, 2)
        self.LblParts = QtWidgets.QLabel(parent=hcmgis_spit_polygon_form)
        self.LblParts.setObjectName("LblParts")
        self.gridLayout.addWidget(self.LblParts, 5, 0, 1, 1)
        self.LblStatus = QtWidgets.QLabel(parent=hcmgis_spit_polygon_form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 11, 0, 1, 2)
        self.status = QtWidgets.QProgressBar(parent=hcmgis_spit_polygon_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 12, 0, 1, 2)
        self.output_file_name = QgsFileWidget(parent=hcmgis_spit_polygon_form)
        self.output_file_name.setObjectName("output_file_name")
        self.gridLayout.addWidget(self.output_file_name, 10, 0, 1, 2)
        self.LblInput = QtWidgets.QLabel(parent=hcmgis_spit_polygon_form)
        self.LblInput.setObjectName("LblInput")
        self.gridLayout.addWidget(self.LblInput, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(parent=hcmgis_spit_polygon_form)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_spit_polygon_form)
        self.BtnApplyClose.accepted.connect(hcmgis_spit_polygon_form.accept) # type: ignore
        self.BtnApplyClose.rejected.connect(hcmgis_spit_polygon_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(hcmgis_spit_polygon_form)

    def retranslateUi(self, hcmgis_spit_polygon_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_spit_polygon_form.setWindowTitle(_translate("hcmgis_spit_polygon_form", " Spilt Polygons into (almost) equal parts by Voronoi Diagram"))
        self.LblRandomPoints.setText(_translate("hcmgis_spit_polygon_form", "Number of random points"))
        self.LblOutput.setText(_translate("hcmgis_spit_polygon_form", "Output"))
        self.LblParts.setText(_translate("hcmgis_spit_polygon_form", "Number of equal parts"))
        self.LblInput.setText(_translate("hcmgis_spit_polygon_form", "Input Polygon"))
from qgsdoublespinbox import QgsDoubleSpinBox
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_spit_polygon_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_spit_polygon_form()
    ui.setupUi(hcmgis_spit_polygon_form)
    hcmgis_spit_polygon_form.show()
    sys.exit(app.exec())
