# Form implementation generated from reading ui file 'hcmgis_reprojection_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hcmgis_reprojection_form(object):
    def setupUi(self, hcmgis_reprojection_form):
        hcmgis_reprojection_form.setObjectName("hcmgis_reprojection_form")
        hcmgis_reprojection_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        hcmgis_reprojection_form.setEnabled(True)
        hcmgis_reprojection_form.resize(370, 288)
        hcmgis_reprojection_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_reprojection_form)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LblInput = QtWidgets.QLabel(parent=hcmgis_reprojection_form)
        self.LblInput.setObjectName("LblInput")
        self.verticalLayout.addWidget(self.LblInput)
        self.CboInput = QgsMapLayerComboBox(parent=hcmgis_reprojection_form)
        self.CboInput.setShowCrs(True)
        self.CboInput.setObjectName("CboInput")
        self.verticalLayout.addWidget(self.CboInput)
        self.LblOutput_4 = QtWidgets.QLabel(parent=hcmgis_reprojection_form)
        self.LblOutput_4.setObjectName("LblOutput_4")
        self.verticalLayout.addWidget(self.LblOutput_4)
        self.crs = QgsProjectionSelectionWidget(parent=hcmgis_reprojection_form)
        self.crs.setObjectName("crs")
        self.verticalLayout.addWidget(self.crs)
        self.LblOutput_3 = QtWidgets.QLabel(parent=hcmgis_reprojection_form)
        self.LblOutput_3.setObjectName("LblOutput_3")
        self.verticalLayout.addWidget(self.LblOutput_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LinOutput = QtWidgets.QLineEdit(parent=hcmgis_reprojection_form)
        self.LinOutput.setEnabled(True)
        self.LinOutput.setMouseTracking(True)
        self.LinOutput.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.LinOutput.setAcceptDrops(False)
        self.LinOutput.setText("")
        self.LinOutput.setReadOnly(False)
        self.LinOutput.setObjectName("LinOutput")
        self.gridLayout.addWidget(self.LinOutput, 0, 0, 1, 1)
        self.BtnOutput = QtWidgets.QPushButton(parent=hcmgis_reprojection_form)
        self.BtnOutput.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.BtnOutput.setFont(font)
        self.BtnOutput.setObjectName("BtnOutput")
        self.gridLayout.addWidget(self.BtnOutput, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.BtnOKCancel = QtWidgets.QDialogButtonBox(parent=hcmgis_reprojection_form)
        self.BtnOKCancel.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.BtnOKCancel.setObjectName("BtnOKCancel")
        self.verticalLayout.addWidget(self.BtnOKCancel)

        self.retranslateUi(hcmgis_reprojection_form)
        self.BtnOKCancel.accepted.connect(hcmgis_reprojection_form.accept) # type: ignore
        self.BtnOKCancel.rejected.connect(hcmgis_reprojection_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(hcmgis_reprojection_form)

    def retranslateUi(self, hcmgis_reprojection_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_reprojection_form.setWindowTitle(_translate("hcmgis_reprojection_form", "Layer Reprojection"))
        self.LblInput.setText(_translate("hcmgis_reprojection_form", "Input Layer"))
        self.LblOutput_4.setText(_translate("hcmgis_reprojection_form", "Target CRS"))
        self.LblOutput_3.setText(_translate("hcmgis_reprojection_form", "Output Shapefile"))
        self.BtnOutput.setText(_translate("hcmgis_reprojection_form", "Browse..."))
from qgis.gui import QgsMapLayerComboBox, QgsProjectionSelectionWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_reprojection_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_reprojection_form()
    ui.setupUi(hcmgis_reprojection_form)
    hcmgis_reprojection_form.show()
    sys.exit(app.exec())
